
["Villager Settings"]
	#Enable Veggies delight villager trades
	enableVillagerTrades = false

["Village Settings"]
	#Enable or disable Veggies Delight village structures
	generateVillageStructures = false

